# Generated by Django 4.1.7 on 2023-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default='comedy', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='directions',
            field=models.ManyToManyField(to='films.direction', verbose_name='Режиcсеры'),
        ),
    ]
